### PR TITLE
Created the API_Response class to hold the API data, error states

### PR DESCRIPTION
**Pull request by Joeroble**
API class created, with error states, this will be used to hold the data, and the results if some other error occurred - such as if no usable data is sent back, data will default to None, user_error will change to True, and connection_error will stay False, if nothing is returned at all, data will stay None, user_error will stay False, and connection_error will turn True.  

This will be used in another part of the program when handling the actual response.

### CODE REVIEW

**Comment by claraj** [comment]
Very useful. 

Something to think about - if `data` is either the data or None, could  `user_error` be None or some information about the user error? Maybe a string that says "invalid request, date in the future" or whatever the problem is - then the Flask UI can display that to the user.   

Similar with `connection_error` - set it to None or something with info about the error, maybe the exception object?

**Comment by Joeroble** [comment]
I thought about including a description field that would contain information about it in the response - such as Success, info on the user error, and storing the exception information.  The idea behind the True/False for user_error/connection_error is to show which one was triggered.  I figured that would be easier to track, and test - is this None, and this True?  Do this, is this None False and this True? Do this, and so on.

**Comment by claraj** [comment]
None is a falsey value in Python, (also empty lists, strings, dictionaries, 0, False and possibly a few other things) so if you use None vs not none, you'll be able to write code like

```
if my_response.data:
     # success, do something with data
elif my_response.user_error:
    # tell user to try again
else: 
    # assume server error, tell user request can't be completed 
```

**Comment by Joeroble** [comment]
still configuring....

**Review by aknayr — APPROVED** [review]

**Pull request merged**
